// Amami Eats — restaurant data
// Each place: name, optional Japanese name, full description, Google Maps short URL,
// resolved lat/lng, tag list, must-visit flag.
const PLACES = [
  {
    name: "Big Dipper",
    description: "Classy restaurant with an awesome view, the shrimp dishes are amazing!",
    url: "https://maps.app.goo.gl/GYs7oK8vqWCeiAAy6",
    lat: 28.4657461, lng: 129.7162562,
    tags: ["dinner", "restaurant", "view", "classy", "seafood", "north"],
    mustVisit: false,
  },
  {
    name: "Holly Camp",
    description: "Nice café with a good vibe, when the owner is there, very nice chats are guaranteed.",
    url: "https://maps.app.goo.gl/NgkKAuUDbnDt5cJf9",
    lat: 28.4678302, lng: 129.6720178,
    tags: ["café", "local-vibe", "north"],
    mustVisit: false,
  },
  {
    name: "Café Mishoran",
    description: "Has a good burger, drinks are good too, but go there for THE view!",
    url: "https://maps.app.goo.gl/rXSVzeE2VhvKSKo76",
    lat: 28.4718227, lng: 129.7158208,
    tags: ["lunch", "restaurant", "view", "burger", "north"],
    mustVisit: false,
  },
  {
    name: "Sand-ya Waraji",
    description: "Must visit! Amazing burritos and crazy good Cuban sandwich. The owner is such a cool vibe as well.",
    url: "https://maps.app.goo.gl/E196E9Tg888boCSD6",
    lat: 28.4388071, lng: 129.6681859,
    tags: ["must-visit", "lunch", "restaurant", "sandwich", "local-vibe", "north"],
    mustVisit: true,
  },
  {
    name: "Vanilla Farm Café",
    description: "Good food and outside seating.",
    url: "https://maps.app.goo.gl/mBzEzJNUyhQTz19SA",
    lat: 28.4336497, lng: 129.6964596,
    tags: ["lunch", "café", "north"],
    mustVisit: false,
  },
  {
    name: "Amami Kyora-umi-kobo Kasari",
    description: "Have some fresh sugar cane juice and food with another spectacular view.",
    url: "https://maps.app.goo.gl/zt8XajdAUXY2cEGaA",
    lat: 28.4035393, lng: 129.6460272,
    tags: ["lunch", "restaurant", "view", "north"],
    mustVisit: false,
  },
  {
    name: "CAFE 安処",
    description: "Excellent choice for breakfast. They also have a very cute treehouse you can access, and the owner's dog is very friendly.",
    url: "https://maps.app.goo.gl/yJ7fzWDNLzPxuZdZ8",
    lat: 28.424394, lng: 129.617393,
    tags: ["breakfast", "café", "local-vibe", "north"],
    mustVisit: false,
  },
  {
    name: "ON SHORE",
    description: "Another breakfast spot, or a chill place in general near the ocean.",
    url: "https://maps.app.goo.gl/YNKJP527NjDHx7t99",
    lat: 28.419338, lng: 129.6200153,
    tags: ["breakfast", "café", "ocean", "north"],
    mustVisit: false,
  },
  {
    name: "アイランドダイナー グリグリ",
    description: "Haven't been there yet, but I've been told it's spectacular.",
    url: "https://maps.app.goo.gl/Cz8NLegDKcunyLbj9",
    lat: 28.4109934, lng: 129.6330567,
    tags: ["dinner", "restaurant", "north"],
    mustVisit: false,
  },
  {
    name: "La Fonte",
    description: "The famous ice cream shop on the island. The passion fruit gelato is great.",
    url: "https://maps.app.goo.gl/HhgdZP26nM3PtX8v6",
    lat: 28.4107306, lng: 129.6299738,
    tags: ["dessert", "ice-cream", "north"],
    mustVisit: false,
  },
  {
    name: "Banya",
    description: "MUST VISIT! Really good Sakana karaage — like OMG please have it. Also lobster dishes.",
    url: "https://maps.app.goo.gl/QHnhfdW7iPbaEEym8",
    lat: 28.4361072, lng: 129.6052873,
    tags: ["must-visit", "dinner", "restaurant", "seafood", "north"],
    mustVisit: true,
  },
  {
    name: "和風茶屋こっち",
    description: "Very high quality lunch. If you happen to get the main table, it has such a vibe too.",
    url: "https://maps.app.goo.gl/sTLkDQKU7qPFMBm5A",
    lat: 28.4217906, lng: 129.5831097,
    tags: ["lunch", "restaurant", "classy", "north"],
    mustVisit: false,
  },
  {
    name: "Amami Island Coffee",
    description: "Try the caramel latte — it simply is the best in the world.",
    url: "https://maps.app.goo.gl/tEFkfhY2oeVZbbRP9",
    lat: 28.4541792, lng: 129.6048577,
    tags: ["café", "north"],
    mustVisit: false,
  },
  {
    name: "Hisakura",
    description: "Very famous keihan place, and very good too.",
    url: "https://maps.app.goo.gl/xrwBSv5K5iYo7U9B7",
    lat: 28.4144495, lng: 129.6016608,
    tags: ["lunch", "restaurant", "keihan", "north"],
    mustVisit: false,
  },
  {
    name: "Manjuca",
    description: "Thai ramen with a lot of style.",
    url: "https://maps.app.goo.gl/Y92aYtwqKimNvoy86",
    lat: 28.4077976, lng: 129.5872689,
    tags: ["lunch", "restaurant", "ramen", "north"],
    mustVisit: false,
  },
  {
    name: "Tecchan",
    description: "They have another branch in Naze, but this is the one to go. Dinner here is top quality.",
    url: "https://maps.app.goo.gl/fxi7zeu1rpGosHTu6",
    lat: 28.3940348, lng: 129.5847481,
    tags: ["dinner", "restaurant", "naze"],
    mustVisit: false,
  },
  {
    name: "得田農園かき氷",
    description: "Best kakigori for a hot day if you happen to be on this side of the island.",
    url: "https://maps.app.goo.gl/K1MbvTFWgKBj52Q96",
    lat: 28.4548556, lng: 129.569387,
    tags: ["dessert", "north"],
    mustVisit: false,
  },
  {
    name: "あらば食堂",
    description: "Very local store, has good soba and the staff are all locals.",
    url: "https://maps.app.goo.gl/mHihyZEAXTJJ9Fux9",
    lat: 28.4465138, lng: 129.5615389,
    tags: ["lunch", "restaurant", "soba", "local-vibe", "north"],
    mustVisit: false,
  },
  {
    name: "みしょれ～奄美Café",
    description: "Good lunch (if a bit far) and nice café too.",
    url: "https://maps.app.goo.gl/xrMQPz3zi273tmvv7",
    lat: 28.4449581, lng: 129.5294372,
    tags: ["lunch", "café", "north"],
    mustVisit: false,
  },
  {
    name: "Mugi no Mi Bakery",
    description: "MUST VISIT — a bakery run by a lovely couple. They do melon pan very often; grab one while they're warm. Insanely good!",
    url: "https://maps.app.goo.gl/qT2iR52mKcSEFDWy7",
    lat: 28.3833192, lng: 129.5744776,
    tags: ["must-visit", "bakery", "local-vibe", "naze"],
    mustVisit: true,
  },
  {
    name: "Shimatofu-ya",
    description: "Healthy food. Tofu here is amazing.",
    url: "https://maps.app.goo.gl/L6TKRyxmP8rZ3mCD9",
    lat: 28.3767681, lng: 129.5682884,
    tags: ["lunch", "restaurant", "healthy", "tofu", "naze"],
    mustVisit: false,
  },
  {
    name: "Brunoa",
    description: "Very good dinner — seriously the best dining place in Naze.",
    url: "https://maps.app.goo.gl/sJs8oR4yyt6TDwhAA",
    lat: 28.392242, lng: 129.5306602,
    tags: ["dinner", "restaurant", "classy", "naze"],
    mustVisit: false,
  },
  {
    name: "むら山",
    description: "Lunch spot — very good quality for a regular lunch place.",
    url: "https://maps.app.goo.gl/d27QDk4U9AgVd5xG6",
    lat: 28.392342, lng: 129.528739,
    tags: ["lunch", "restaurant", "naze"],
    mustVisit: false,
  },
  {
    name: "Amami Yagijima Hotel",
    description: "The hotel restaurant opens for lunch and dinner. Not even expensive for what it is — nice food, nice restaurant, nice view.",
    url: "https://maps.app.goo.gl/wgHhPccmgPz1R5oj8",
    lat: 28.3992271, lng: 129.5071563,
    tags: ["lunch", "dinner", "restaurant", "view", "naze"],
    mustVisit: false,
  },
  {
    name: "Noodle shop 祐",
    description: "I think this shop sells the best soy ramen in the country.",
    url: "https://maps.app.goo.gl/LiAqqU4w8nY3vNbDA",
    lat: 28.3677747, lng: 129.4991987,
    tags: ["lunch", "restaurant", "ramen", "naze"],
    mustVisit: false,
  },
  {
    name: "257Coffee",
    description: "The prosciutto sandwich here — omg. Breakfasts in general are good. Drinks too.",
    url: "https://maps.app.goo.gl/vwFY61mPfy8FDLt36",
    lat: 28.3754058, lng: 129.4975877,
    tags: ["breakfast", "café", "sandwich", "naze"],
    mustVisit: false,
  },
  {
    name: "Go Action",
    description: "Some of the best burgers I've ever tried. They're huge too.",
    url: "https://maps.app.goo.gl/HL9hrtvcGsoMCiSV6",
    lat: 28.3768879, lng: 129.4921211,
    tags: ["lunch", "dinner", "restaurant", "burger", "naze"],
    mustVisit: false,
  },
  {
    name: "架空食堂 kurau",
    description: "Classy dinner.",
    url: "https://maps.app.goo.gl/NFsjJL1YT2XDQd2q6",
    lat: 28.3795812, lng: 129.4915988,
    tags: ["dinner", "restaurant", "classy", "naze"],
    mustVisit: false,
  },
  {
    name: "Pousser",
    description: "Classy lunch.",
    url: "https://maps.app.goo.gl/cwMcEntDLE8rkojN9",
    lat: 28.3806044, lng: 129.4925657,
    tags: ["lunch", "restaurant", "classy", "naze"],
    mustVisit: false,
  },
  {
    name: "ナチュールスタイルソノダ",
    description: "Classy dinner, amazing pizza btw.",
    url: "https://maps.app.goo.gl/Pc5UsQXgy7vLzxeK9",
    lat: 28.3796869, lng: 129.4897367,
    tags: ["dinner", "restaurant", "classy", "pizza", "naze"],
    mustVisit: false,
  },
  {
    name: "くしやきバル masa",
    description: "Very nice yakitori — order the apple pizza, it's very unique and amazing.",
    url: "https://maps.app.goo.gl/3xrU5rUMhuodgumK9",
    lat: 28.3803708, lng: 129.4918635,
    tags: ["dinner", "restaurant", "yakitori", "naze"],
    mustVisit: false,
  },
  {
    name: "Dandan",
    description: "If you want to meet the locals for real, with amazing food, this is the one.",
    url: "https://maps.app.goo.gl/WZsx7FAgNEX7pv6E6",
    lat: 28.3956673, lng: 129.4948109,
    tags: ["dinner", "restaurant", "local-vibe", "naze"],
    mustVisit: false,
  },
  {
    name: "Westerner's Café",
    description: "Must visit! Decent coffee, but order the Cowboy's Lunch — top casual lunch for the not-so-hungry days.",
    url: "https://maps.app.goo.gl/e4THdjnjrTHjFSLt6",
    lat: 28.3506947, lng: 129.3278048,
    tags: ["must-visit", "lunch", "café", "central"],
    mustVisit: true,
  },
  {
    name: "Bee Lunch",
    description: "I recommend everything, but mostly: talk to the owners — lovely couple.",
    url: "https://maps.app.goo.gl/dk5eaqcPaW2vxGo1A",
    lat: 28.3733476, lng: 129.4070895,
    tags: ["lunch", "restaurant", "local-vibe", "central"],
    mustVisit: false,
  },
  {
    name: "Uken Shokudō",
    description: "Another very good keihan and overall good restaurant.",
    url: "https://maps.app.goo.gl/SicyXd7eVMXZUtJJ6",
    lat: 28.2744597, lng: 129.2960131,
    tags: ["lunch", "restaurant", "keihan", "central"],
    mustVisit: false,
  },
  {
    name: "食事処 とうぐら",
    description: "A slow and easy place. It used to be a school — they restored it and preserved it as a restaurant/hotel.",
    url: "https://maps.app.goo.gl/vVPwkn2PJRik272J8",
    lat: 28.2332295, lng: 129.2532646,
    tags: ["lunch", "dinner", "restaurant", "local-vibe", "south"],
    mustVisit: false,
  },
  {
    name: "道の駅レストラン マングローブ",
    description: "Delicious food, amazing maguro. If you do the mangrove canoe trip, stop by here!",
    url: "https://maps.app.goo.gl/wZyxcCDRBy6zxVt47",
    lat: 28.259651, lng: 129.4089075,
    tags: ["lunch", "restaurant", "seafood", "central"],
    mustVisit: false,
  },
  {
    name: "Kanou",
    description: "This place is literally inside a ranch — and run by a very lovely couple too.",
    url: "https://maps.app.goo.gl/CvEhirxhiq4JyzDEA",
    lat: 28.2245161, lng: 129.3005985,
    tags: ["dinner", "restaurant", "local-vibe", "south"],
    mustVisit: false,
  },
  {
    name: "Seafood Restaurant",
    description: "Go to the one on the second floor — incredibly good maguro don.",
    url: "https://maps.app.goo.gl/AAqAmHgchsK6SZaG7",
    lat: 28.1453127, lng: 129.3089242,
    tags: ["lunch", "restaurant", "seafood", "south"],
    mustVisit: false,
  },
  {
    name: "canau cafe (カナウカフェ)",
    description: "Lovely staff, good pizza.",
    url: "https://maps.app.goo.gl/tpEvsfBtiiWUnfWeA",
    lat: 28.148572, lng: 129.3105871,
    tags: ["lunch", "café", "pizza", "south"],
    mustVisit: false,
  },
  {
    name: "Fujien Tea Shop",
    description: "Very good coffee, nice cakes. Try the matcha latte… jeeeeeeesus christ!",
    url: "https://maps.app.goo.gl/JeE7uzigFdBrb7kv6",
    lat: 28.1469103, lng: 129.310737,
    tags: ["café", "south"],
    mustVisit: false,
  },
  {
    name: "Maruya",
    description: "Famous local restaurant with amazing seafood.",
    url: "https://maps.app.goo.gl/VoY9HNFcdQUFdtzw6",
    lat: 28.1474684, lng: 129.312361,
    tags: ["dinner", "restaurant", "seafood", "local-vibe", "south"],
    mustVisit: false,
  },
  {
    name: "Pas Parfait",
    description: "Another place that feels good for the environment/vibe, right in front of the ocean.",
    url: "https://maps.app.goo.gl/VwiD5TqfT7XeM4kF7",
    lat: 28.1351931, lng: 129.3300076,
    tags: ["café", "ocean", "view", "south"],
    mustVisit: false,
  },
];
